version: '3.0'
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    restart: on-failure
    environment:
      - PORT=${APP_PORT}
      - DEBUG_PORT=${APP_DEBUG_PORT}
    env_file: ../.env
    command: npm run start
