version: '3.0'

services:
  client:
    extends:
      file: ./client/compose-service.yml
      service: client

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - .nginx:/etc/nginx

  main:
    extends:
      file: ./api/compose-service.yml
      service: main

  main-cockroachdb:
    extends:
      file: ./api/compose-service.yml
      service: main-cockroachdb

  main-prisma:
    extends:
      file: ./api/compose-service.yml
      service: main-prisma
    depends_on:
      - main-cockroachdb