version: '3'

services:
  cockroachdb:
    container_name: api-cockroachdb
    image: cockroachdb/cockroach:v23.1.13
    restart: on-failure
    ports:
      - 26257
      - ${API_COCKROACHDB_ADMIN_PORT}:${API_COCKROACHDB_ADMIN_PORT}
    volumes:
      - './cockroach-data/cockroachdb:/cockroach/cockroach-data'
    command: start-single-node --insecure --http-port ${API_COCKROACHDB_ADMIN_PORT}

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app-network

  main:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on:
      - cockroachdb
      - redis
    ports:
      - "80:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
