version: '3.0'

services:
  client:
    extends:
      file: ./client/docker-compose.yml
      service: client
    networks:
      - main

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .nginx:/etc/nginx
    networks:
      - main

networks:
  main:

  
  # api:
  #   extends:
  #     file: ./api/docker-compose.yml
  #     service: api

  # cockroachdb:
  #   extends:
  #     file: ./api/docker-compose.yml
  #     service: cockroachdb

  # prisma:
  #   extends:
  #     file: ./api/docker-compose.yml
  #     service: prisma

  # redis:
  #   extends:
  #     file: ./api/docker-compose.yml
  #     service: redis
