version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - .nginx:/etc/nginx
    profiles:
      - production

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./client/Dockerfile
      target: production
    restart: on-failure
    ports:
      - ${APP_DEBUG_PORT}:${APP_DEBUG_PORT}
    environment:
      - PORT=${APP_PORT}
      - DEBUG_PORT=${APP_DEBUG_PORT}
    env_file: .env
    command: npm run start
    profiles:
      - production

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
      target: production
    restart: on-failure
    ports:
      - ${API_DEBUG_PORT}:${API_DEBUG_PORT}
    environment:
      - PORT=${API_PORT}
      - DEBUG_PORT=${API_DEBUG_PORT}
    env_file: .env
    profiles:
      - production

  api-cockroachdb:
    extends:
      file: ./api/libs/api/compose-service.yml
      service: api-cockroachdb
    profiles:
      - development
      - production

  api-prisma:
    extends:
      file: ./api/libs/api/compose-service.yml
      service: api-prisma
    depends_on:
      - api-cockroachdb
    profiles:
      - development
      - production
