version: '3.0'

services:
  client:
    extends:
      file: ./client/docker-compose.yml
      service: client

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - .nginx:/etc/nginx

  api:
    extends:
      file: ./api/docker-compose.yml
      service: api

  cockroachdb:
    extends:
      file: ./api/docker-compose.yml
      service: cockroachdb

  prisma:
    extends:
      file: ./api/docker-compose.yml
      service: prisma
    depends_on:
      - cockroachdb

  redis:
    extends:
      file: ./api/docker-compose.yml
      service: redis

networks:
  main:
