version: '3.0'

services:
  client:
    extends:
      file: ./client/docker-compose.yml
      service: client
    networks:
      - main

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - .nginx:/etc/nginx
    networks:
      - main

  api:
    extends:
      file: ./api/docker-compose.yml
      service: api
    networks:
      - main

  cockroachdb:
    extends:
      file: ./api/docker-compose.yml
      service: cockroachdb
    networks:
      - main

  prisma:
    extends:
      file: ./api/docker-compose.yml
      service: prisma
    depends_on:
      - cockroachdb
    networks:
      - main

  redis:
    extends:
      file: ./api/docker-compose.yml
      service: redis
    networks:
      - main

networks:
  main:
