version: '0.1'

services:
  redis:
    extends:
      file: ./api/docker-compose.yml
      service: redis

  api:
    extends:
      file: ./api/docker-compose.yml
      service: api

  cockroachdb:
    extends:
      file: ./api/docker-compose.yml
      service: cockroachdb

  prisma:
    extends:
      file: ./api/docker-compose.yml
      service: prisma