version: '3.0'

services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}nginx
    image: nginx:latest
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./lib/.nginx:/etc/nginx
    profiles:
      - production

  client:
    container_name: ${COMPOSE_PROJECT_NAME}client
    build:
      context: .
      dockerfile: ./client/Dockerfile
      target: production
    restart: on-failure
    environment:
      - PORT=${APP_PORT}
      - DEBUG_PORT=${APP_DEBUG_PORT}
    env_file: .env
    command: npm run start
    profiles:
      - production

  api:
    container_name: ${COMPOSE_PROJECT_NAME}api
    build:
      context: .
      dockerfile: ./api/Dockerfile
      target: production
    restart: on-failure
    environment:
      - PORT=${API_PORT}
      - DEBUG_PORT=${API_DEBUG_PORT}
    env_file: .env
    profiles:
      - production

  api-cockroachdb:
    extends:
      file: ./api/libs/api/compose-service.yml
      service: api-cockroachdb
    container_name: ${COMPOSE_PROJECT_NAME}api-cockroachdb
    profiles:
      - development

  api-prisma:
    extends:
      file: ./api/libs/api/compose-service.yml
      service: api-prisma
    depends_on:
      - api-cockroachdb
    container_name: ${COMPOSE_PROJECT_NAME}api-prisma
    profiles:
      - development

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}redis
    image: redis:latest
    restart: on-failure
    ports:
      - 6379:6379
    profiles:
      - development
