version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3.9-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app-network

  account-service:
    build:
      context: .
      dockerfile: ./server/services/account/Dockerfile
    depends_on:
      - rabbitmq
      - redis
    networks:
      - app-network
  
  mcs-service:
    build:
      context: .
      dockerfile: ./server/services/impactium/Dockerfile
    depends_on:
      - rabbitmq
      - redis
    networks:
      - app-network

  gateway:
    build:
      context: .
      dockerfile: ./server/gateway/Dockerfile
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "80:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
