version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    restart: on-failure
    volumes:
      - .:/usr/src/app
      - ./secrets:/etc/secrets
    ports:
      - ${API_PORT}:${API_PORT}
      - ${API_DEBUG_PORT}:${API_DEBUG_PORT}
    environment:
      - PORT=${API_PORT}
      - DEBUG_PORT=${API_DEBUG_PORT}
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/secrets/dev_firebase_sa.json
      - GCLOUD_TRANSLATE_CREDENTIALS=/etc/secrets/dev_gcloud_translate_sa.json
      - GOOGLE_PLAY_CREDENTIALS=/etc/secrets/dev_google_play_sa.json
    env_file: ../../dev.env
    command: npm run start:debug

  api-cockroachdb:
    container_name: api-cockroachdb
    image: cockroachdb/cockroach:v23.1.13
    restart: on-failure
    ports:
      - 26257
      - ${API_COCKROACHDB_ADMIN_PORT}:${API_COCKROACHDB_ADMIN_PORT}
    volumes:
      - './cockroach-data/cockroachdb:/cockroach/cockroach-data'
    command: start-single-node --insecure --http-port ${API_COCKROACHDB_ADMIN_PORT}

  api-prisma-studio:
    container_name: api-prisma-studio
    image: node:20-alpine
    restart: on-failure
    working_dir: '/usr/src/app'
    ports:
      - ${API_PRISMA_STUDIO_PORT}:${API_PRISMA_STUDIO_PORT}
    volumes:
      - ./prisma:/usr/src/app/prisma
    env_file: ../../dev.env
    command: npx prisma studio --port ${API_PRISMA_STUDIO_PORT}