version: '3.8'
services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: on-failure
    volumes:
      - .:/api
      - ../lib:/lib
    ports:
      - ${API_PORT}:${API_PORT}
      - ${API_DEBUG_PORT}:${API_DEBUG_PORT}
    environment:
      - PORT=${API_PORT}
      - DEBUG_PORT=${API_DEBUG_PORT}
    env_file: ../.env
    command: npm run start:debug

  main-cockroachdb:
    container_name: main-cockroachdb
    image: cockroachdb/cockroach:v23.1.13
    restart: on-failure
    ports:
      - 26257
      - ${API_COCKROACHDB_ADMIN_PORT}:${API_COCKROACHDB_ADMIN_PORT}
    volumes:
      - './cockroach-data/cockroachdb:/cockroach/cockroach-data'
    command: start-single-node --insecure --http-port ${API_COCKROACHDB_ADMIN_PORT}

  main-prisma:
    container_name: main-prisma
    image: node:20-alpine
    restart: on-failure
    working_dir: '/api'
    ports:
      - ${API_PRISMA_STUDIO_PORT}:${API_PRISMA_STUDIO_PORT}
    volumes:
      - ./prisma:/usr/src/app/prisma
    env_file: ../.env
    command: npx prisma studio --port ${API_PRISMA_STUDIO_PORT}