version: '3.0'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile.prod
      target: production
    restart: on-failure
    environment:
      - PORT=3001
      - DEBUG_PORT=${API_DEBUG_PORT}
    env_file: ../.env
    networks:
      - main
    command: npm run start:prod

  cockroachdb:
    container_name: cockroachdb
    image: cockroachdb/cockroach:v23.1.13
    restart: on-failure
    ports:
      - 26257
      - 1488:1488
    volumes:
      - './cockroach-data/cockroachdb:/cockroach/cockroach-data'
    networks:
      - main
    command: start-single-node --insecure --http-port 1488

  prisma:
    container_name: prisma
    image: node:20-alpine
    restart: on-failure
    working_dir: /
    ports:
      - ${API_PRISMA_STUDIO_PORT}:${API_PRISMA_STUDIO_PORT}
    volumes:
      - ./prisma:/prisma
    env_file: ../.env
    networks:
      - main
    command: npx prisma studio --port ${API_PRISMA_STUDIO_PORT}

  # redis:
  #   container_name: redis
  #   image: "redis:latest"
  #   restart: on-failure
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis-data:/data
  #   networks:
  #     - main