name: "@impactium/console"

on:
  push:
    paths:
      - 'lib/console/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Подготовка к деплою
        uses: actions/checkout@v3

      - name: Установка Node.js
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: ./lib/console/package-lock.json
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Установка зависимостей
        working-directory: lib/console
        run: npm install

      - name: Сборка пакета
        working-directory: lib/console
        run: npm run build

      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
